#phpmyadmin perlu sedikit di optimasi agar lebih aman.
#kopi file nginx.conf ke direktori /etc pada image phpmyadmin:latest
#beri nama image yang baru menjadi phpmyadmin-custom
FROM phpmyadmin
COPY nginx.conf /etc
